## Numpy

In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 4])
array1

array([1, 2, 4])

In [3]:
array2  = np.array([[1.4, 2.1, 3.3], [4, 5, 6]])
array2

array([[1.4, 2.1, 3.3],
       [4. , 5. , 6. ]])

In [4]:
array1.dtype

dtype('int64')

In [5]:
float(array2[0][0])

1.4

- Vectorization and Broadcasting

In [6]:
array1 + 1.5

array([2.5, 3.5, 5.5])

In [7]:
array1 * array2

array([[ 1.4,  4.2, 13.2],
       [ 4. , 10. , 24. ]])

In [8]:
np.sqrt(array2)

array([[1.18321596, 1.44913767, 1.81659021],
       [2.        , 2.23606798, 2.44948974]])

In [9]:
np.sum(array2, axis=0), np.sum(array2, axis=1)

(array([5.4, 7.1, 9.3]), array([ 6.8, 15. ]))

In [12]:
array2 = array1[:]
array2, array1

(array([1, 2, 4]), array([1, 2, 4]))

In [13]:
array2*2, array1

(array([2, 4, 8]), array([1, 2, 4]))

## Pandas